config-version: 4
config:
  lang: en
logs:
  show_save_logs: true
data:
  save_all_data_in: 20 #in minutes
  method: LOCAL #LOCAL OR DATABASE
  database_config:
    config_host:
      host: 127.0.0.1
      port: 3306
    credentials:
      user: user123
      password: 1234
    database_config:
      database_name: StorageMechanic
      driver: mysql