messages:
  commands:
    custom_blocks:
      get:
        valid_id: "<green> you have received: %id%"
        invalid_id: "<red>Invalid ID"
  storage:
    search_page_invalid: "<red>Please enter a valid page!"
    search_page_enter: "<red>Please enter a valid page!"