inventory:
  id: searchItemAnvil #modifiable
  type: ANVIL #not modifiable
  title: '<white><shift:-60>%oraxen_anvilsearchitem% <shift:-200>Search items' #modifiable
  slots:
    blocked_slots: [1-3,5-7] #modifiable
    data_slots: [9-35] #modifiable
    items:
      - "research_item:5" #modifiable only slots
      - "close_item:4" #modifiable only slots
      - "open_result_inv_item:3" #modifiable only slots
      - "next_item:8" #modifiable only slots
      - "back_item:0" #modifiable only slots
#      - "blocked_item1:1" #modifiable can you add more blocked items
      - "repair_item:999" #not modifiable
      - "result_lore:998" #not modifiable
items:
  research_item: #not modifiable
    type: RESEARCH_ITEM #not modifiable
    amount: 1 #modifiable
    item: or:sm_search_item #modifiable
    display: "<dark_green>Click to research" #modifiable
    lore:
      - "<gold>Searching: <yellow>%search_status%" #modifiable can you add more lines of lore
  result_lore: #not modifiable
    type: RESULT_LORE #not modifiable
    lore: #modifiable can you add more lines of lore
      - "<red>Click to get on close!" 
      - "<red>Page: <aqua>%page% <red>slot: <aqua>%slot%"
  open_result_inv_item: #not modifiable
    type: OPEN_RESULT_INV_ITEM #not modifiable
    item: or:sm_sort_item #modifiable
    amount: 1 #modifiable
    display: '<dark_green>Open results menu' #modifiable
  close_item: #not modifiable
    type: CLOSE_ITEM #not modifiable
    item: mc:barrier #modifiable
    amount: 1 #modifiable
    display: '<dark_red>Close' #modifiable
  next_item: #not modifiable
    type: NEXT_ITEM #not modifiable
    item: or:sm_next_page #modifiable
    amount: 1 #modifiable
    display: '<gold>Next >>' #modifiable
  back_item: #not modifiable
    type: BACK_ITEM #not modifiable
    item: or:sm_back_page #modifiable
    amount: 1 #modifiable
    display: '<gold><< Back' #modifiable
  repair_item: #not modifiable
    type: REPAIR_ITEM #not modifiable
    item: or:sm_null_item #modifiable
    amount: 1 #modifiable
  blocked_item1: #modifiable can you add more blocked items only
    type: BLOCKED_ITEM #not modifiable
    item: or:sm_blocked_item #modifiable
    amount: 1 #modifiable