inventory:
  id: searchItemAnvilResult #modifiable
  type: CHEST #modifiable
  rows: 6 #modifiable
  title: '<white><shift:-8>%oraxen_anvilsearchresult% <shift:-252>Search result:' #modifiable
  slots:
    blocked_slots: [1-3,5-7] #modifiable
    data_slots: [0-44] #modifiable
    items:
      - "open_anvil:49" #modifiable only slots
      - "next_item:53" #modifiable only slots
      - "back_item:45" #modifiable only slots
#      - "blocked_item1:46" #modifiable you add more blocked items only blocked items!
      - "result_lore:998" #not modifiable
items:
  result_lore: #not modifiable
    type: RESULT_LORE #not modifiable
    lore:
      - "<red>Page: <aqua>%page% <red>slot: <aqua>%slot%" #modifiable can you add more lore lines
  open_anvil: #not modifiable
    type: OPEN_ANVIL #not modifiable
    item: or:sm_search_item #modifiable
    amount: 1 #modifiable
    display: '<gold>Open Search menu' #modifiable
  next_item: #not modifiable
    type: NEXT_ITEM #not modifiable
    item: or:sm_next_page #modifiable
    amount: 1 #modifiable
    display: '<gold>Next >>'
  back_item: #not modifiable
    type: BACK_ITEM #not modifiable
    item: or:sm_back_page
    amount: 1 #modifiable
    display: '<gold><< Back' #modifiable
  blocked_item1: #modifiable can you add more blocked items!
    type: BLOCKED_ITEM #not modifiable
    item: mc:stone #modifiable
    amount: 1 #modifiable
    display: 'test' #modifiable
    lore:
      - 'test' #modifiable can you add more lore lines!